# Generated by Django 4.0.2 on 2022-02-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rasm', models.FileField(upload_to='bolimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('batafsil', models.CharField(max_length=300)),
                ('rasm', models.FileField(upload_to='mahsulotlar')),
                ('brend', models.CharField(max_length=30)),
                ('mamalakat', models.CharField(max_length=30)),
                ('vazn', models.CharField(max_length=30)),
                ('narx', models.IntegerField()),
                ('mavjud', models.BooleanField(default=True)),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosy.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Sharh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.PositiveSmallIntegerField(default=1)),
                ('matn', models.CharField(max_length=300)),
                ('sana', models.DateField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosy.mahsulot')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.mijoz')),
            ],
        ),
    ]
